@hostname = http://localhost:9000/api
# @hostname = https://api.dclinicas.com.br/api
@contentType = application/json
@accessToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGluaWNJZCI6ImE1YjMzMDMxLTU5ZTMtNGQxMi1hOTNmLTgxOGE0MWMyNzhlMSIsInVzZXIiOnsiaWQiOiJkMmE4MTgxNC0xYjc3LTQ3YjktOTQ5OS0yMzgxMTYxNDhjYjciLCJmdWxsTmFtZSI6ImRjaSBzdXBvcnRlIiwiZW1haWwiOiJkY2lAZGNpc3Vwb3J0ZS5jb20uYnIiLCJhZG1pbiI6InJvb3QiLCJjb3ZlckltYWdlIjpudWxsfSwiaWF0IjoxNzMwMTI0ODM0LCJleHAiOjE3MzI3MTY4MzR9.vbJHAsMdbBYWK1FRLZCGBmy13tFycQn0MHcRmBz_GTg

@refreshToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGluaWNJZCI6ImE1YjMzMDMxLTU5ZTMtNGQxMi1hOTNmLTgxOGE0MWMyNzhlMSIsInVzZXIiOnsiaWQiOiJkMmE4MTgxNC0xYjc3LTQ3YjktOTQ5OS0yMzgxMTYxNDhjYjciLCJmdWxsTmFtZSI6ImRjaSBzdXBvcnRlIiwiZW1haWwiOiJkY2lAZGNpc3Vwb3J0ZS5jb20uYnIiLCJhZG1pbiI6InJvb3QiLCJjb3ZlckltYWdlIjpudWxsfSwiaWF0IjoxNzMwMTI0ODM0LCJleHAiOjE3MzI3MTY4MzR9.vbJHAsMdbBYWK1FRLZCGBmy13tFycQn0MHcRmBz_GTg

### SUCCESS
POST {{hostname}}/auth HTTP/1.1
Content-Type: {{contentType}}

{
  "code": "010-010",
  "email": "dci@dcisuporte.com.br",
  "password": "dci@6913"
}

### SUCCESS
POST {{hostname}}/auth/refresh-token HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{refreshToken}}

{
}

###
POST {{hostname}}/users HTTP/1.1
Content-Type: {{contentType}}

{
  "fullName": "Campo fullName obrigatório!",
  "email": "teste@teste.com.br",
  "password": "123456",
  "confirmPassword": "123456"
}

###
GET {{hostname}}/users HTTP/1.1
Content-Type: {{contentType}}
Authorization:{{accessToken}}

{
}

###
GET {{hostname}}/users/39d13466-f343-45df-9207-e988a94ece0a HTTP/1.1
Content-Type: {{contentType}}
Authorization:{{accessToken}}

{
}

### CLINIC - create
POST {{hostname}}/clinics HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{accessToken}}

{
  "fantasy":"Campo obrigatório",
  "title":"Campo obrigatório",
  "cnpj":"12.345.678/9999-99",
  "ie": "",
  "phone":"(98) 7653-2111",
  "address":"",
  "number":"",
  "complement":"",
  "reference":"",
  "city":"",
  "state":"",
  "zipCode":""
}

### CLINICS - update
PUT {{hostname}}/clinics/17a3faa1-c5cc-4f5f-88b7-e36944061b3d HTTP/1.1
Content-Type: {{contentType}}
Authorization:{{accessToken}}

{
  "fantasy":"TESTE",
  "title":"TESTE",
  "cnpj":"12.345.678/9999-99",
  "ie": "TSTE",
  "phone":"(98) 7653-2111",
  "address":"",
  "number":"",
  "complement":"",
  "reference":"",
  "city":"",
  "state":"",
  "zipCode":""
}

### CLINICS - average-service
PUT {{hostname}}/clinics/17a3faa1-c5cc-4f5f-88b7-e36944061b3d/average-service HTTP/1.1
Content-Type: {{contentType}}
Authorization:{{accessToken}}

{
  "time": "00:20"
}

### CLINICS - show all
GET {{hostname}}/clinics?limit=15&page=1&title=&fantasy= HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{accessToken}}

{
}

### CLINICS - show unique
GET {{hostname}}/clinics/a5b33031-59e3-4d12-a93f-818a41c278e1 HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{accessToken}}

{
}

### CLINICS - show all works
GET {{hostname}}/clinics/a5b33031-59e3-4d12-a93f-818a41c278e1/works HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{accessToken}}

{
}

### CLINICS - delete
DELETE {{hostname}}/clinics/80028469-3636-4c5d-a5af-ed60d924d506 HTTP/1.1
Content-Type: {{contentType}}
Authorization:{{accessToken}}

{
}

### CLINICS - update works
PUT {{hostname}}/clinics/17a3faa1-c5cc-4f5f-88b7-e36944061b3d/works HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{accessToken}}

[
  {
    "clinicId": "17a3faa1-c5cc-4f5f-88b7-e36944061b3d",
    "week": "Terça",
    "open": "false",
    "times": [{"description":"Abre à(s)","time":"08:00"},{"description":"Fecha à(s)","time":"12:00"}]
  }
]

### CLINICS - update works-service
PUT {{hostname}}/clinics/17a3faa1-c5cc-4f5f-88b7-e36944061b3d/works-service HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{accessToken}}

[
  {
    "clinicId": "17a3faa1-c5cc-4f5f-88b7-e36944061b3d",
    "week": "Terça",
    "open": "true",
    "times": [{"description":"Abre à(s)","time":"09:00"},{"description":"Fecha à(s)","time":"13:00"}]
  },
  {
    "clinicId": "17a3faa1-c5cc-4f5f-88b7-e36944061b3d",
    "week": "Domingo",
    "open": "false",
    "times": [{"description":"Abre à(s)","time":"09:00"},{"description":"Fecha à(s)","time":"13:00"}]
  }
]

### CLINICS CHART - show chart
GET {{hostname}}/clinics/charts HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{accessToken}}

{
}

### ROOMS - show all
GET {{hostname}}/rooms?room= HTTP/1.1
Content-Type: {{contentType}}
Authorization:{{accessToken}}

{
}

### ROOMS
GET {{hostname}}/rooms/6b8e8160-3b5f-491c-9b48-c3f9914679c3 HTTP/1.1
Content-Type: {{contentType}}
Authorization:{{accessToken}}

{
}

### ROOMS
POST {{hostname}}/rooms HTTP/1.1
Content-Type: {{contentType}}
Authorization:{{accessToken}}

{
  "clinicId": "17a3faa1-c5cc-4f5f-88b7-e36944061b3d",
  "room": "Depilação",
  "description": ""
}

### ROOMS
PUT {{hostname}}/rooms/6b8e8160-3b5f-491c-9b48-c3f9914679c3 HTTP/1.1
Content-Type: {{contentType}}
Authorization:{{accessToken}}

{
  "clinicId": "17a3faa1-c5cc-4f5f-88b7-e36944061b3d",
  "code": "001",
  "room": "Depilação",
  "description": "",
  "averageService": "00:30",
  "active": true
}

### ROOMS
PUT {{hostname}}/rooms/6b8e8160-3b5f-491c-9b48-c3f9914679c3/active-inative HTTP/1.1
Content-Type: {{contentType}}
Authorization:{{accessToken}}

{
}


### PEOPLE - show all
GET {{hostname}}/peoples?full_name=&limit=15&page=1 HTTP/1.1
Content-Type: {{contentType}}
Authorization:{{accessToken}}

{
}

### PEOPLES - show unique
GET {{hostname}}/peoples/3e5732f4-040e-4923-8ba1-cda76755e64f HTTP/1.1
Content-Type: {{contentType}}
Authorization:{{accessToken}}

{
}

### PEOPLES - create
POST {{hostname}}/peoples HTTP/1.1
Content-Type: {{contentType}}
Authorization:{{accessToken}}

{
  "fullName": "Renan"
}


#"dateOfBirth": "01/01/1990",
### PEOPLES - update
PUT {{hostname}}/peoples/3e5732f4-040e-4923-8ba1-cda76755e64f HTTP/1.1
Content-Type: {{contentType}}
Authorization:{{accessToken}}

{
  "fullName": "Renan - Editado",
  "document": "000.000.000-00",
  "dateOfBirth": "01/01/1990",
  "phones": [{ "phone": "11 99999-9999", "description": "Celular" }],
  "email": "renan@dcisuporte.com.br",
  "type": "specialist",
  "address": "Amaral Lyra",
  "number": "1155",
  "neighborhood": "Centro",
  "complement": "",
  "reference": "",
  "city": "Itápolis",
  "state": "SP",
  "zipCode": "14990-203"
}

### PEOPLES - delete
DELETE {{hostname}}/peoples/3e5732f4-040e-4923-8ba1-cda76755e64f HTTP/1.1
Content-Type: {{contentType}}
Authorization:{{accessToken}}

{
}

### People - active-inative
PUT {{hostname}}/peoples/c8f95fbb-8301-4b86-a97d-598239c991dc/active-inative HTTP/1.1
Content-Type: {{contentType}}
Authorization:{{accessToken}}

{
}

### People - active-inative
GET {{hostname}}/peoples/active-inative HTTP/1.1
Content-Type: {{contentType}}
Authorization:{{accessToken}}

{
}

### EXPENSES - show all
GET {{hostname}}/expenses?description=energia HTTP/1.1
Content-Type: {{contentType}}
Authorization:{{accessToken}}

{
}

### EXPENSES
GET {{hostname}}/expenses/6b8e8160-3b5f-491c-9b48-c3f9914679c3 HTTP/1.1
Content-Type: {{contentType}}
Authorization:{{accessToken}}

{
}

### EXPENSES
POST {{hostname}}/expenses HTTP/1.1
Content-Type: {{contentType}}
Authorization:{{accessToken}}

{
  "clinicId": "a5b33031-59e3-4d12-a93f-818a41c278e1",
  "description": "Aluguel"
}

### EXPENSES
PUT {{hostname}}/expenses/a830b495-48a9-46f7-adbd-0e5c37926e59 HTTP/1.1
Content-Type: {{contentType}}
Authorization:{{accessToken}}

{
  "description": "Depilação",
  "type": "variable",
  "active": false
}

### EXPENSES
PUT {{hostname}}/expenses/c38ccc35-29a5-4a45-862e-61b865d26cc2/active-inative HTTP/1.1
Content-Type: {{contentType}}
Authorization:{{accessToken}}

{
}

### EXPENSES
PUT {{hostname}}/expenses/c38ccc35-29a5-4a45-862e-61b865d26cc2/types/active-inative HTTP/1.1
Content-Type: {{contentType}}
Authorization:{{accessToken}}

{
}

### EXPENSES
DELETE {{hostname}}/expenses/c38ccc35-29a5-4a45-862e-61b865d26cc2 HTTP/1.1
Content-Type: {{contentType}}
Authorization:{{accessToken}}

{
}
