name: 🚀 DEPLOY API DANIELA FIDELLIS

on:
  push:
    branches:
      - master

jobs:
  script_work:
    name: Work in Server
    runs-on: ubuntu-latest
    steps:
      - name: Work Deploy in Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DANIELA_FIDELLIS_HOST }}
          username: ${{ secrets.DANIELA_FIDELLIS_USER }}
          password: ${{ secrets.DANIELA_FIDELLIS_PASS }}
          port: 22022
          script: |
            cd /home/dclinica/public_html/api
            chmod +x ./entrypoint.sh
            ./entrypoint.sh
